on: [pull_request]
jobs:
  migration-check:
    runs-on: ubuntu-latest
    name: Checks migration files
    steps:
      - name: Check migration files step
        id: migrations
        uses: waveaccounting/migration-check-action@add-datateam-as-reviewer
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          project-type: rails
